name: CI

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
  
env:
  IMAGE_NAME: hello-world-server

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to DockerHub
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Extract version from Git tag
      id: vars
      run: |
        VERSION=${GITHUB_REF_NAME#v}
        echo "tag=${GITHUB_REF_NAME}"   >> "$GITHUB_OUTPUT"
          
    - name: Build the Docker image
      uses: docker/build-push-action@v6.18.0
      with:
        context: .
        push: true
        tags: |
           ${{ github.actor }}/${{ env.IMAGE_NAME }}:latest
           ${{ github.actor }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.tag }}

    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v3.0.0
      with:
        token: ${{ secrets.PAT }}
        repository:  ${{ github.actor }}/${{ env.IMAGE_NAME }}-helm
        event-type: new-version
        client-payload: '{"image": "${{ github.actor }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.tag }}"}'
